@file:OptIn(ExperimentalJsExport::class)

import dev.dootah.generated.OfferScreen
import ui.toJson

/**
 * GENERATED BY DOOTAH -- DO NOT EDIT
 *
 * The bundle's entry points, declared in the root package on purpose.
 *
 * `@JsExport` mirrors the Kotlin package into the exported object, so a
 * declaration in `dev.dootah.generated` is reachable only as
 * `globalThis["dootah-bundle"].dev.dootah.generated.renderScreen`. The Android
 * runtime calls `globalThis["dootah-bundle"].renderScreen()`, so the exported
 * entry points have to sit at the root while the generated screens stay
 * packaged.
 */

@JsExport
fun renderScreen(): String = OfferScreen.render().toJson()

@JsExport
fun handleAction(action: String): String = OfferScreen.handle(action).toJson()

fun main() {}
