package dev.dootah.gradle

import org.gradle.api.GradleException

/** Bundle code is generated by Dootah and uses its own toolchain, independently of the host. */
internal const val BUNDLE_KOTLIN_VERSION = "2.3.20"

internal data class CompilerBackend(val family: String, val compilerVersion: String) {
    val artifactId: String get() = if (family == "2.3") "dootah-compiler-plugin" else "dootah-compiler-plugin-kotlin-$family"
    val explicitOrdering: Boolean get() = requireNotNull(compilerFeatures.getProperty(compilerVersion)) {
        "Dootah compiler compatibility metadata is incomplete for Kotlin $compilerVersion. Reinstall this Dootah release."
    } == "explicit"
}

private val compilerFeatures by lazy {
    java.util.Properties().apply {
        requireNotNull(DootahProjectPlugin::class.java.getResourceAsStream("/dev/dootah/compiler-features.properties")) {
            "Dootah compiler feature metadata is missing. Reinstall this Dootah release."
        }.use(::load)
    }
}

/** This resource is also the build/test matrix; support cannot drift from artifact production. */
internal val compilerBackends: List<CompilerBackend> by lazy {
    val matrix = java.util.Properties()
    requireNotNull(DootahProjectPlugin::class.java.getResourceAsStream("/dev/dootah/compiler-backends.properties")) {
        "Dootah compiler backend matrix is missing from the Gradle plugin. Reinstall this Dootah release."
    }.use(matrix::load)
    matrix.stringPropertyNames().sorted().flatMap { family ->
        matrix.getProperty(family).split(",").map { CompilerBackend(family, it.trim()) }
    }
}

internal fun selectCompilerBackend(hostKotlinVersion: String): CompilerBackend =
    resolveCompilerBackend(hostKotlinVersion) ?: throw GradleException(unsupportedCompilerMessage(hostKotlinVersion))

internal fun resolveCompilerBackend(hostKotlinVersion: String): CompilerBackend? =
    compilerBackends.singleOrNull { it.compilerVersion == hostKotlinVersion }

internal fun unsupportedCompilerMessage(version: String): String =
    "Detected Kotlin $version.\n" +
        "No verified Dootah compiler ABI is available.\n" +
        "Verified ranges (only tested releases; no inferred patch compatibility): " +
        compilerBackends.groupBy { it.family }.entries.joinToString { (family, versions) ->
            "$family [${versions.joinToString { it.compilerVersion }}]"
        } + ".\nDootah has not modified the application."

internal fun hostKotlinVersion(project: org.gradle.api.Project): String? =
    configuredCompilerVersion(project.extensions.findByName("kotlin")) ?: hostKgpVersion(project)

/** Newer KGP can select a different compiler. Reflection bridges this optional public API. */
internal fun configuredCompilerVersion(extension: Any?): String? {
    if (extension == null) return null
    val getter = extension.javaClass.methods.firstOrNull { it.name == "getCompilerVersion" && it.parameterCount == 0 } ?: return null
    return try {
        val version = getter.invoke(extension) as? org.gradle.api.provider.Provider<*>
        version?.orNull as? String
    } catch (_: ReflectiveOperationException) {
        // Never guess KGP's version when an explicitly configurable compiler
        // exists but cannot be read. No backend will match this diagnostic.
        "unknown (compiler configuration could not be read)"
    }
}

internal fun hostKgpVersion(project: org.gradle.api.Project): String? =
    project.plugins.withType(org.jetbrains.kotlin.gradle.plugin.KotlinBasePlugin::class.java)
        .firstOrNull()?.pluginVersion

internal fun verifyKotlinVersion(hostKotlinVersion: String) { selectCompilerBackend(hostKotlinVersion) }

internal fun hostCompilerBackend(project: org.gradle.api.Project): CompilerBackend =
    hostKotlinVersion(project)?.let(::selectCompilerBackend)
        ?: throw GradleException("Dootah could not detect the project's Kotlin compiler. Apply the Kotlin Android or JVM plugin.")

/** The failure text used when Dootah is declared after the Compose plugin. */
internal fun composeDeclaredFirstMessage(): String =
    "Dootah must be declared before the Compose compiler plugin, because " +
        "Dootah's transform runs in plugin declaration order and Compose must " +
        "lower Dootah's generated composable calls afterwards.\n" +
        "Reorder the app's plugins block:\n" +
        "    plugins {\n" +
        "        id(\"dev.dootah\")\n" +
        "        id(\"org.jetbrains.kotlin.plugin.compose\")\n" +
        "    }"

/**
 * The Dootah release these plugins belong to.
 *
 * Read from the jar so the compiler plugin, the annotation and the bundle
 * runtime cannot drift apart from the Gradle plugin that wires them.
 */
internal val DOOTAH_VERSION: String
    get() = DootahProjectPlugin::class.java.`package`?.implementationVersion
        ?: requireNotNull(DootahProjectPlugin::class.java.getResourceAsStream("/dev/dootah/release-version.txt"))
            .bufferedReader().use { it.readText().trim() }
