package dev.dootah.gradle

import org.gradle.api.GradleException

/** Bundle code is generated by Dootah and uses its own toolchain, independently of the host. */
internal const val BUNDLE_KOTLIN_VERSION = "2.3.20"

internal data class CompilerBackend(val family: String, val compilerVersion: String) {
    val artifactId: String get() = if (family == "2.3") "dootah-compiler-plugin" else "dootah-compiler-plugin-kotlin-$family"
}

/** This resource is also the build/test matrix; support cannot drift from artifact production. */
internal val compilerBackends: List<CompilerBackend> by lazy {
    val matrix = java.util.Properties()
    requireNotNull(DootahProjectPlugin::class.java.getResourceAsStream("/dev/dootah/compiler-backends.properties")) {
        "Dootah compiler backend matrix is missing from the Gradle plugin. Reinstall this Dootah release."
    }.use(matrix::load)
    matrix.stringPropertyNames().sorted().flatMap { family ->
        matrix.getProperty(family).split(",").map { CompilerBackend(family, it.trim()) }
    }
}

internal fun selectCompilerBackend(hostKotlinVersion: String): CompilerBackend =
    compilerBackends.singleOrNull { it.compilerVersion == hostKotlinVersion }
        ?: throw GradleException(
            "Dootah has no verified compiler backend for Kotlin $hostKotlinVersion. " +
                "Supported Kotlin versions: ${compilerBackends.joinToString { it.compilerVersion }}. " +
                "Use a Dootah release that supports your Kotlin version, or select a supported Kotlin version. " +
                "Compiler ABI checks cannot be bypassed."
        )

internal fun verifyKotlinVersion(hostKotlinVersion: String) { selectCompilerBackend(hostKotlinVersion) }

internal fun hostCompilerBackend(project: org.gradle.api.Project): CompilerBackend =
    project.plugins.withType(org.jetbrains.kotlin.gradle.plugin.KotlinBasePlugin::class.java)
        .firstOrNull()?.let { selectCompilerBackend(it.pluginVersion) }
        ?: throw GradleException("Dootah could not detect the project's Kotlin compiler. Apply the Kotlin Android or JVM plugin.")

/** The failure text used when Dootah is declared after the Compose plugin. */
internal fun composeDeclaredFirstMessage(): String =
    "Dootah must be declared before the Compose compiler plugin, because " +
        "Dootah's transform runs in plugin declaration order and Compose must " +
        "lower Dootah's generated composable calls afterwards.\n" +
        "Reorder the app's plugins block:\n" +
        "    plugins {\n" +
        "        id(\"dev.dootah\")\n" +
        "        id(\"org.jetbrains.kotlin.plugin.compose\")\n" +
        "    }"

/**
 * The Dootah release these plugins belong to.
 *
 * Read from the jar so the compiler plugin, the annotation and the bundle
 * runtime cannot drift apart from the Gradle plugin that wires them.
 */
internal val DOOTAH_VERSION: String
    get() = DootahProjectPlugin::class.java.`package`?.implementationVersion
        ?: requireNotNull(DootahProjectPlugin::class.java.getResourceAsStream("/dev/dootah/release-version.txt"))
            .bufferedReader().use { it.readText().trim() }
