package dev.dootah.gradle.internal

import java.io.File

/** Root project name of the synthesized bundle build. */
const val BUNDLE_BUILD_NAME: String = "dootah-bundle-build"

/**
 * The UMD global the Android runtime looks the bundle up under, and the name of
 * the file webpack produces.
 *
 * Both derive from the bundle build's *root project name*, not from any Kotlin
 * option -- `outputModuleName` renames the intermediate module and leaves the
 * webpack library alone. So the generated settings file pins the root project
 * name to this value, and the Android runtime's BUNDLE_MODULE_NAME must match
 * it. Changing either without the other breaks the bundle protocol silently:
 * the bundle loads and then exports nothing the runtime can find.
 */
const val BUNDLE_MODULE_NAME: String = "dootah-bundle"

/**
 * Writes the Gradle build that compiles generated Kotlin into `bundle.js`.
 *
 * A separate, included build rather than a project inside the host's build. An
 * Android application build cannot host a Kotlin/JS target, and adding the
 * Kotlin Multiplatform plugin to a second project in the same build loads the
 * Kotlin Gradle plugin twice, which Gradle warns may break the build. An
 * included build gets its own plugin classloader, so the host's Kotlin setup and
 * the bundle's cannot interfere.
 *
 * Everything written here lives under `build/` and is never edited by hand; it
 * is regenerated whenever the host build configures.
 */
internal fun writeBundleBuild(
    buildDirectory: File,
    kotlinVersion: String,
    dootahVersion: String,
): File {

    val generatedSources = File(buildDirectory, GENERATED_SOURCES_PATH)
    generatedSources.mkdirs()

    File(buildDirectory, "settings.gradle.kts").writeText(
        """
        // GENERATED BY DOOTAH -- DO NOT EDIT
        pluginManagement {
            repositories {
                mavenLocal()
                gradlePluginPortal()
                mavenCentral()
            }
        }

        dependencyResolutionManagement {
            repositories {
                mavenLocal()
                mavenCentral()
            }
        }

        // Pinned: webpack names its output after this, and the Android
        // runtime resolves the bundle through a global of the same name.
        rootProject.name = "$BUNDLE_MODULE_NAME"
        """.trimIndent() + "\n"
    )

    File(buildDirectory, "build.gradle.kts").writeText(
        """
        // GENERATED BY DOOTAH -- DO NOT EDIT
        plugins {
            kotlin("multiplatform") version "$kotlinVersion"
        }

        kotlin {
            js {
                browser()
                binaries.executable()
            }

            sourceSets {
                jsMain {
                    kotlin.setSrcDirs(listOf("$GENERATED_SOURCES_PATH"))

                    dependencies {
                        implementation("dev.dootah:dootah-bundle-runtime:$dootahVersion")
                    }
                }
            }
        }
        """.trimIndent() + "\n"
    )

    return generatedSources
}

internal const val GENERATED_SOURCES_PATH = "generated/jsMain/kotlin"
