package dev.dootah.compiler.generate

import dev.dootah.compiler.model.BundleAction
import dev.dootah.compiler.model.BundleCommandModel
import dev.dootah.compiler.model.BundleExpression
import dev.dootah.compiler.model.BundleFunction
import dev.dootah.compiler.model.BundleModifier
import dev.dootah.compiler.model.BundleParameter
import dev.dootah.compiler.model.BundleScreen
import dev.dootah.compiler.model.BundleStatement
import dev.dootah.compiler.model.BundleUi

internal const val GENERATED_PACKAGE = "dev.dootah.generated"

private const val GENERATED_HEADER =
    "// GENERATED BY DOOTAH FROM %s -- DO NOT EDIT"

/**
 * Emits the bundle-side Kotlin for a screen, and the entry points the runtime
 * calls.
 *
 * Kotlin rather than JavaScript on purpose: Kotlin/JS turns this into the
 * bundle, so the generator never has to reason about JavaScript semantics, and
 * the generated code is checked by the same compiler that checked the source it
 * came from. A generator emitting JavaScript would have no such safety net.
 */
internal object BundleSourceWriter {

    /** The screen implementation, in its own package. */
    fun writeScreen(screen: BundleScreen): String = buildString {

        appendLine(GENERATED_HEADER.format(screen.functionName))
        appendLine("package $GENERATED_PACKAGE")
        appendLine()
        appendLine("import protocol.Command")
        appendLine("import protocol.ScreenArguments")
        appendLine("import protocol.ScreenState")
        appendLine("import ui.BoxNode")
        appendLine("import ui.BundleModifier")
        appendLine("import ui.BundleNode")
        appendLine("import ui.ButtonNode")
        appendLine("import ui.ColumnNode")
        appendLine("import ui.NativeSlotNode")
        appendLine("import ui.RowNode")
        appendLine("import ui.TextNode")
        appendLine()
        appendLine("internal object ${screenObjectName(screen)} {")
        appendLine()
        appendLine("    const val SCREEN_ID: String = ${kotlinStringLiteral(screen.screenId)}")
        appendLine()

        appendRender(screen)
        appendLine()
        appendPerform(screen)

        screen.functions.forEach { function ->
            appendLine()
            appendFunction(function)
        }

        appendLine("}")
    }

    private fun StringBuilder.appendRender(screen: BundleScreen) {

        appendLine(
            "    fun render(arguments: ScreenArguments, state: ScreenState): BundleNode {"
        )

        appendPrelude(screen, indent = 8)

        append("        return ")
        append(renderRootUi(screen.ui, indent = 8))
        appendLine("    }")
    }

    /**
     * Emits the action handler.
     *
     * The screen's declarations are repeated here because an action may read
     * them, and because they are pure: recomputing them is cheaper and safer
     * than carrying a render's locals across a call from the app.
     */
    private fun StringBuilder.appendPerform(screen: BundleScreen) {

        appendLine(
            "    fun perform(" +
                "action: String, arguments: ScreenArguments, state: ScreenState" +
                "): List<Command> {"
        )
        appendLine("        val commands = mutableListOf<Command>()")

        appendPrelude(screen, indent = 8)

        if (screen.actions.isEmpty()) {
            appendLine("        // This screen has no actions.")
        } else {
            appendLine("        when (action) {")
            screen.actions.forEach { action -> appendAction(action, indent = 12) }
            appendLine("        }")
        }

        appendLine("        return commands")
        appendLine("    }")
    }

    private fun StringBuilder.appendAction(action: BundleAction, indent: Int) {

        val pad = " ".repeat(indent)

        appendLine("$pad${kotlinStringLiteral(action.name)} -> {")
        action.body.forEach { statement -> append(renderStatement(statement, indent + 4)) }
        appendLine("$pad}")
    }

    private fun StringBuilder.appendPrelude(screen: BundleScreen, indent: Int) {

        val pad = " ".repeat(indent)

        screen.parameters.forEach { parameter ->
            appendLine(
                "$pad" + "val ${parameter.name}: ${parameter.declaredType()} = " +
                    "arguments.${parameter.accessor()}" +
                    "(${kotlinStringLiteral(parameter.name)})"
            )
        }

        screen.prelude.forEach { statement -> append(renderStatement(statement, indent)) }
    }

    private fun StringBuilder.appendFunction(function: BundleFunction) {

        val parameters = function.parameters.joinToString(", ") { parameter ->
            "${parameter.name}: ${parameter.declaredType()}"
        }

        appendLine(
            "    private fun ${function.name}($parameters): " +
                "${function.returnType.kotlinName} =\n" +
                "        ${renderExpression(function.body)}"
        )
    }

    /**
     * The entry points the installed runtime calls.
     *
     * Declared in the root package because `@JsExport` mirrors the Kotlin
     * package into the exported object: a packaged `renderScreen` is reachable
     * only as `globalThis["dootah-bundle"].dev.dootah.generated.renderScreen`,
     * which is not what the runtime looks for.
     *
     * Every screen is dispatched by its own id and can only reach its own
     * object, so one screen cannot be served another's implementation, and each
     * gets its own state.
     */
    fun writeExports(screens: List<ScreenEntry>): String = buildString {

        appendLine("@file:OptIn(ExperimentalJsExport::class)")
        appendLine()
        appendLine("// GENERATED BY DOOTAH -- DO NOT EDIT")
        appendLine()
        screens.forEach { screen -> appendLine("import $GENERATED_PACKAGE.${screen.objectName}") }
        appendLine("import protocol.Command")
        appendLine("import protocol.ScreenArguments")
        appendLine("import protocol.ScreenState")
        appendLine("import protocol.envelope")
        appendLine("import protocol.failure")
        appendLine("import protocol.parseArguments")
        appendLine("import protocol.screenIdsJson")
        appendLine("import protocol.unknownScreen")
        appendLine("import ui.BundleNode")
        appendLine()
        appendLine("/** One store per screen, so no screen can see another's state. */")
        appendLine("private val screenStates = HashMap<String, ScreenState>()")
        appendLine()
        appendLine("private fun stateFor(screenId: String): ScreenState =")
        appendLine("    screenStates.getOrPut(screenId) { ScreenState() }")
        appendLine()
        appendLine("@JsExport")
        appendLine("fun screenIds(): String = screenIdsJson(")
        appendLine("    listOf(")
        screens.forEach { screen -> appendLine("        ${screen.objectName}.SCREEN_ID,") }
        appendLine("    )")
        appendLine(")")
        appendLine()
        appendLine("@JsExport")
        appendLine("fun renderScreen(screenId: String, argumentsJson: String): String = try {")
        appendLine("    val state = stateFor(screenId)")
        appendLine("    val arguments = parseArguments(argumentsJson)")
        appendLine("    val ui = renderOf(screenId, arguments, state)")
        appendLine("    if (ui == null) unknownScreen(screenId) else envelope(ui, emptyList())")
        appendLine("} catch (failure: Throwable) {")
        appendLine("    failure(failure.message ?: \"the screen could not be rendered\")")
        appendLine("}")
        appendLine()
        appendLine("@JsExport")
        appendLine("fun handleAction(")
        appendLine("    screenId: String,")
        appendLine("    action: String,")
        appendLine("    argumentsJson: String,")
        appendLine("): String = try {")
        appendLine("    val state = stateFor(screenId)")
        appendLine("    val arguments = parseArguments(argumentsJson)")
        appendLine("    val commands = performOn(screenId, action, arguments, state)")
        appendLine("    val ui = renderOf(screenId, arguments, state)")
        appendLine("    if (commands == null || ui == null) unknownScreen(screenId)")
        appendLine("    else envelope(ui, commands)")
        appendLine("} catch (failure: Throwable) {")
        appendLine("    failure(failure.message ?: \"the action could not be handled\")")
        appendLine("}")
        appendLine()
        appendLine("private fun renderOf(")
        appendLine("    screenId: String,")
        appendLine("    arguments: ScreenArguments,")
        appendLine("    state: ScreenState,")
        appendLine("): BundleNode? = when (screenId) {")
        screens.forEach { screen ->
            appendLine(
                "    ${screen.objectName}.SCREEN_ID -> " +
                    "${screen.objectName}.render(arguments, state)"
            )
        }
        appendLine("    else -> null")
        appendLine("}")
        appendLine()
        appendLine("private fun performOn(")
        appendLine("    screenId: String,")
        appendLine("    action: String,")
        appendLine("    arguments: ScreenArguments,")
        appendLine("    state: ScreenState,")
        appendLine("): List<Command>? = when (screenId) {")
        screens.forEach { screen ->
            appendLine(
                "    ${screen.objectName}.SCREEN_ID -> " +
                    "${screen.objectName}.perform(action, arguments, state)"
            )
        }
        appendLine("    else -> null")
        appendLine("}")
        appendLine()
        appendLine("fun main() {}")
    }

    fun screenObjectName(screen: BundleScreen): String = screenObjectName(screen.screenId)

    fun screenObjectName(screenId: String): String =
        "DootahScreen_${sanitizeForIdentifier(screenId)}"

    // ---- statements -----------------------------------------------------

    private fun renderStatement(statement: BundleStatement, indent: Int): String {

        val pad = " ".repeat(indent)

        return when (statement) {

            is BundleStatement.DeclareValue ->
                "$pad" + "val ${statement.name}: ${statement.type.kotlinName} = " +
                    "${renderExpression(statement.value)}\n"

            is BundleStatement.DeclareState ->
                "$pad" + "state.init${statement.type.kotlinName}(" +
                    "${kotlinStringLiteral(statement.name)}, " +
                    "${renderExpression(statement.initial)})\n"

            is BundleStatement.Assign ->
                "$pad" + "state.set${statement.type.kotlinName}(" +
                    "${kotlinStringLiteral(statement.name)}, " +
                    "${renderExpression(statement.value)})\n"

            is BundleStatement.Perform ->
                "$pad" + "commands.add(${renderCommand(statement.command)})\n"

            is BundleStatement.Conditional -> buildString {
                appendLine("$pad" + "if (${renderExpression(statement.condition)}) {")
                statement.ifTrue.forEach { append(renderStatement(it, indent + 4)) }
                appendLine("$pad} else {")
                statement.ifFalse.forEach { append(renderStatement(it, indent + 4)) }
                appendLine("$pad}")
            }
        }
    }

    private fun renderCommand(command: BundleCommandModel): String = when (command) {

        is BundleCommandModel.InvokeCallback ->
            "Command.InvokeCallback(${kotlinStringLiteral(command.name)})"

        is BundleCommandModel.Log -> "Command.Log(${renderExpression(command.message)})"

        is BundleCommandModel.Toast -> "Command.Toast(${renderExpression(command.message)})"
    }

    // ---- UI -------------------------------------------------------------

    /**
     * Emits the screen's root, which is a value rather than a child to add.
     *
     * An `if` at the root chooses between whole layouts, so it is emitted as an
     * `if` expression. Lowering has already established that every branch
     * produces exactly one of them.
     */
    private fun renderRootUi(ui: BundleUi, indent: Int): String {

        val pad = " ".repeat(indent)

        if (ui !is BundleUi.ConditionalUi) return renderUi(ui, indent).trimStart()

        return buildString {
            appendLine("if (${renderExpression(ui.condition)}) {")
            append("$pad    ")
            append(renderRootUi(ui.ifTrue.single(), indent + 4))
            appendLine("$pad} else {")
            append("$pad    ")
            append(renderRootUi(ui.ifFalse.single(), indent + 4))
            appendLine("$pad}")
        }
    }

    private fun renderUi(ui: BundleUi, indent: Int): String {

        val pad = " ".repeat(indent)

        return when (ui) {

            is BundleUi.ColumnUi -> container("ColumnNode", ui.modifiers, ui.children, indent)
            is BundleUi.RowUi -> container("RowNode", ui.modifiers, ui.children, indent)
            is BundleUi.BoxUi -> container("BoxNode", ui.modifiers, ui.children, indent)

            is BundleUi.TextUi ->
                "$pad" + "TextNode(${renderExpression(ui.text)}" +
                    modifierArgument(ui.modifiers) + ")\n"

            is BundleUi.ButtonUi ->
                "$pad" + "ButtonNode(${renderExpression(ui.label)}, " +
                    "${kotlinStringLiteral(ui.action)}" +
                    modifierArgument(ui.modifiers) + ")\n"

            is BundleUi.NativeSlotUi ->
                "$pad" + "NativeSlotNode(${kotlinStringLiteral(ui.slot)})\n"

            // Only ever a child, so it is emitted as the statements that add its
            // branch's children rather than as a node of its own.
            is BundleUi.ConditionalUi -> buildString {
                appendLine("$pad" + "if (${renderExpression(ui.condition)}) {")
                ui.ifTrue.forEach { append(addChild(it, indent + 4)) }
                appendLine("$pad} else {")
                ui.ifFalse.forEach { append(addChild(it, indent + 4)) }
                appendLine("$pad}")
            }
        }
    }

    private fun container(
        node: String,
        modifiers: List<BundleModifier>,
        children: List<BundleUi>,
        indent: Int,
    ): String {

        val pad = " ".repeat(indent)

        return buildString {
            appendLine("$pad$node(")
            appendLine("$pad    modifiers = ${renderModifiers(modifiers)},")
            appendLine("$pad    children = buildList {")
            children.forEach { child -> append(addChild(child, indent + 8)) }
            appendLine("$pad    },")
            appendLine("$pad)")
        }
    }

    /**
     * Adds one child to the list being built.
     *
     * A conditional contributes zero, one or several children depending on the
     * branch taken, which is why children are built into a list rather than
     * written out as a fixed sequence.
     */
    private fun addChild(child: BundleUi, indent: Int): String {

        val pad = " ".repeat(indent)

        if (child is BundleUi.ConditionalUi) return renderUi(child, indent)

        return "$pad" + "add(" + renderUi(child, 0).trim() + ")\n"
    }

    private fun modifierArgument(modifiers: List<BundleModifier>): String =
        if (modifiers.isEmpty()) "" else ", ${renderModifiers(modifiers)}"

    private fun renderModifiers(modifiers: List<BundleModifier>): String {

        if (modifiers.isEmpty()) return "emptyList()"

        return "listOf(" + modifiers.joinToString(", ") { renderModifier(it) } + ")"
    }

    private fun renderModifier(modifier: BundleModifier): String = when (modifier) {

        is BundleModifier.Inherited -> "BundleModifier.Inherited"

        is BundleModifier.Padding ->
            "BundleModifier.Padding(${modifier.start}, ${modifier.top}, " +
                "${modifier.end}, ${modifier.bottom})"

        is BundleModifier.FillMaxWidth -> "BundleModifier.FillMaxWidth(${modifier.fraction})"
        is BundleModifier.FillMaxHeight -> "BundleModifier.FillMaxHeight(${modifier.fraction})"
        is BundleModifier.FillMaxSize -> "BundleModifier.FillMaxSize(${modifier.fraction})"

        is BundleModifier.Size ->
            "BundleModifier.Size(${modifier.width}, ${modifier.height})"

        is BundleModifier.Width -> "BundleModifier.Width(${modifier.value})"
        is BundleModifier.Height -> "BundleModifier.Height(${modifier.value})"
        is BundleModifier.Weight -> "BundleModifier.Weight(${modifier.value})"

        is BundleModifier.Background -> "BundleModifier.Background(${modifier.color}L)"
    }

    // ---- expressions ----------------------------------------------------

    private fun renderExpression(expression: BundleExpression): String = when (expression) {

        is BundleExpression.IntConstant -> expression.value.toString()

        is BundleExpression.StringConstant -> kotlinStringLiteral(expression.value)

        is BundleExpression.BooleanConstant -> expression.value.toString()

        is BundleExpression.LocalReference -> expression.name

        is BundleExpression.StateReference ->
            "state.${expression.type.accessor}(${kotlinStringLiteral(expression.name)})"

        is BundleExpression.Arithmetic ->
            "(${renderExpression(expression.left)} ${expression.operator.symbol} " +
                "${renderExpression(expression.right)})"

        is BundleExpression.Comparison ->
            "(${renderExpression(expression.left)} ${expression.operator.symbol} " +
                "${renderExpression(expression.right)})"

        is BundleExpression.Logical ->
            "(${renderExpression(expression.left)} ${expression.operator.symbol} " +
                "${renderExpression(expression.right)})"

        is BundleExpression.Not -> "(!${renderExpression(expression.value)})"

        is BundleExpression.Negate -> "(-${renderExpression(expression.value)})"

        is BundleExpression.Conditional ->
            "(if (${renderExpression(expression.condition)}) " +
                "${renderExpression(expression.ifTrue)} else " +
                "${renderExpression(expression.ifFalse)})"

        is BundleExpression.Invoke ->
            "${expression.functionName}(" +
                expression.arguments.joinToString(", ") { renderExpression(it) } + ")"

        is BundleExpression.Interpolation -> renderInterpolation(expression)
    }

    /**
     * Emits a template as concatenation rather than as a Kotlin template.
     *
     * A leading empty literal is added whenever the first part is not itself a
     * string, so every `+` is `String.plus`. Without it a template beginning
     * with a number would emit `Int.plus(String)`, which does not compile -- and
     * re-emitting a real Kotlin template would mean escaping `$` correctly in
     * every literal part instead.
     */
    private fun renderInterpolation(interpolation: BundleExpression.Interpolation): String {

        val parts = interpolation.parts

        if (parts.all { it is BundleExpression.StringConstant }) {
            val joined = parts.joinToString("") { (it as BundleExpression.StringConstant).value }
            return kotlinStringLiteral(joined)
        }

        val needsStringAnchor = parts.firstOrNull() !is BundleExpression.StringConstant
        val rendered = parts.map { renderExpression(it) }

        return if (needsStringAnchor) {
            (listOf("\"\"") + rendered).joinToString(" + ")
        } else {
            rendered.joinToString(" + ")
        }
    }
}

/** One screen the exports file dispatches to. */
internal data class ScreenEntry(
    val screenId: String,
    val objectName: String,
)

private fun BundleParameter.declaredType(): String =
    type.kotlinName + if (isNullable) "?" else ""

private fun BundleParameter.accessor(): String =
    if (isNullable) "${type.accessor}OrNull" else type.accessor
