package dev.dootah.compiler.generate

import dev.dootah.compiler.model.BundleExpression
import dev.dootah.compiler.model.BundleScreen
import dev.dootah.compiler.model.BundleUi

private const val GENERATED_PACKAGE = "dev.dootah.generated"

private const val GENERATED_HEADER =
    "// GENERATED BY DOOTAH FROM %s -- DO NOT EDIT"

/**
 * Emits the bundle-side Kotlin for one screen.
 *
 * Kotlin rather than JavaScript on purpose: Kotlin/JS turns this into the
 * bundle, so the generator never has to reason about JavaScript semantics, and
 * the generated code is checked by the same compiler that checked the source it
 * came from. A generator emitting JavaScript would have no such safety net.
 */
internal object BundleSourceWriter {

    /** The screen implementation, in its own package. */
    fun writeScreen(screen: BundleScreen): String {

        val body = StringBuilder()

        body.appendLine(GENERATED_HEADER.format(screen.functionName))
        body.appendLine("package $GENERATED_PACKAGE")
        body.appendLine()
        body.appendLine("import ui.BundleNode")
        body.appendLine("import ui.Column")
        body.appendLine()
        body.appendLine("internal object ${screenObjectName(screen)} {")
        body.appendLine()
        body.appendLine("    const val SCREEN_ID: String = ${kotlinStringLiteral(screen.screenId)}")
        body.appendLine()
        body.appendLine("    fun render(): BundleNode {")

        screen.locals.forEach { local ->
            body.appendLine(
                "        val ${local.name}: ${local.type.kotlinName} = " +
                    renderExpression(local.value)
            )
        }

        if (screen.locals.isNotEmpty()) body.appendLine()

        body.append(renderUi(screen.ui, indent = 8, isRoot = true))

        body.appendLine("    }")
        body.appendLine("}")

        return body.toString()
    }

    /**
     * The entry points the installed runtime calls.
     *
     * Declared in the root package because `@JsExport` mirrors the Kotlin
     * package into the exported object: a packaged `renderScreen` is reachable
     * only as `globalThis["dootah-bundle"].dev.dootah.generated.renderScreen`,
     * which is not what the runtime looks for.
     */
    fun writeExports(screen: BundleScreen): String = buildString {

        appendLine("@file:OptIn(ExperimentalJsExport::class)")
        appendLine()
        appendLine(GENERATED_HEADER.format(screen.functionName))
        appendLine()
        appendLine("import $GENERATED_PACKAGE.${screenObjectName(screen)}")
        appendLine("import ui.toJson")
        appendLine()
        appendLine("@JsExport")
        appendLine(
            "fun renderScreen(): String = ${screenObjectName(screen)}.render().toJson()"
        )
        appendLine()
        appendLine("@JsExport")
        appendLine(
            "fun handleAction(action: String): String = " +
                "${screenObjectName(screen)}.render().toJson()"
        )
        appendLine()
        appendLine("fun main() {}")
    }

    fun screenObjectName(screen: BundleScreen): String =
        "DootahScreen_${sanitizeForIdentifier(screen.screenId)}"

    // ---- UI -------------------------------------------------------------

    private fun renderUi(ui: BundleUi, indent: Int, isRoot: Boolean): String {

        val pad = " ".repeat(indent)

        return when (ui) {

            is BundleUi.ColumnUi -> buildString {
                appendLine("$pad${if (isRoot) "return " else ""}Column {")
                ui.children.forEach { child ->
                    append(renderUi(child, indent + 4, isRoot = false))
                }
                appendLine("$pad}")
            }

            is BundleUi.TextUi ->
                "$pad" + "Text(${renderExpression(ui.text)})\n"

            is BundleUi.ButtonUi ->
                "$pad" + "Button(text = ${renderExpression(ui.label)}, " +
                    "action = ${kotlinStringLiteral(ui.action)})\n"
        }
    }

    // ---- expressions ----------------------------------------------------

    private fun renderExpression(expression: BundleExpression): String =
        when (expression) {

            is BundleExpression.IntConstant -> expression.value.toString()

            is BundleExpression.StringConstant -> kotlinStringLiteral(expression.value)

            is BundleExpression.BooleanConstant -> expression.value.toString()

            is BundleExpression.LocalReference -> expression.name

            is BundleExpression.Arithmetic ->
                "(${renderExpression(expression.left)} " +
                    "${expression.operator.symbol} " +
                    "${renderExpression(expression.right)})"

            is BundleExpression.Interpolation -> renderInterpolation(expression)
        }

    /**
     * Emits a template as concatenation rather than as a Kotlin template.
     *
     * A leading empty literal is added whenever the first part is not itself a
     * string, so every `+` is `String.plus`. Without it a template beginning
     * with a number would emit `Int.plus(String)`, which does not compile -- and
     * re-emitting a real Kotlin template would mean escaping `$` correctly in
     * every literal part instead.
     */
    private fun renderInterpolation(interpolation: BundleExpression.Interpolation): String {

        val parts = interpolation.parts

        if (parts.all { it is BundleExpression.StringConstant }) {
            val joined = parts.joinToString("") { (it as BundleExpression.StringConstant).value }
            return kotlinStringLiteral(joined)
        }

        val needsStringAnchor = parts.firstOrNull() !is BundleExpression.StringConstant
        val rendered = parts.map { renderExpression(it) }

        return if (needsStringAnchor) {
            (listOf("\"\"") + rendered).joinToString(" + ")
        } else {
            rendered.joinToString(" + ")
        }
    }
}
